import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import TanstackqueryProvider from "@/lib/TanstackqueryProvider";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import "@/styles/reset.css";
const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSans.variable}`}>
        <TanstackqueryProvider>
          <AppRouterCacheProvider>{children}</AppRouterCacheProvider>
        </TanstackqueryProvider>
      </body>
    </html>
  );
}
